kotlin.code.style=official

# Kotlin compiler memory
kotlin.daemon.jvmargs=-Xmx4g

# Gradle memory
org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=2g -Dfile.encoding=UTF-8

# Prevent too many parallel processes consuming RAM
org.gradle.workers.max=2
org.gradle.parallel=false

# Android
android.nonTransitiveRClass=true
android.useAndroidX=true
