name: Build Debug iOS IPA

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-ios:
    name: Build Debug iOS IPA
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build KMP
        run: |
          ./gradlew build \
            --no-daemon \
            --max-workers=2

      - name: Show Xcode schemes
        run: |
          xcodebuild \
            -project iosApp/iosApp.xcodeproj \
            -list

      - name: Archive Debug iOS App
        run: |
          xcodebuild archive \
            -project iosApp/iosApp.xcodeproj \
            -scheme iosApp \
            -configuration Debug \
            -sdk iphoneos \
            -archivePath "$PWD/build/iosApp-Debug.xcarchive" \
            CODE_SIGNING_ALLOWED=NO

      - name: Create IPA folder
        run: mkdir -p build/ipa/Payload

      - name: Find Debug App
        run: |
          find build/iosApp-Debug.xcarchive \
            -type d \
            -name "*.app"

      - name: Create Debug IPA
        run: |
          APP_PATH=$(find build/iosApp-Debug.xcarchive/Products/Applications \
            -type d \
            -name "*.app" | head -n 1)

          echo "Found app: $APP_PATH"

          cp -R "$APP_PATH" build/ipa/Payload/

          cd build/ipa

          zip -r ../Debug-iOS-App.ipa Payload

      - name: Show generated IPA
        run: |
          ls -lh build/Debug-iOS-App.ipa

      - name: Upload Debug IPA
        uses: actions/upload-artifact@v4
        with:
          name: Debug-iOS-IPA
          path: build/Debug-iOS-App.ipa
          retention-days: 30
